### ISSUE TITLE
Unclear data format to return in Hanoi problem

### ISSUE THREAD

**Issue by datbayev** [adnanaziz/EPIJudge#10]
The 16.1 problem (The Tower of Hanoi)

In the book It is asked to print out all the moves. But in the [java source](https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_java/epi/Hanoi.java) code you expect to return `List<List<Integer>>`, which is misleading. I had to dig into `computeTowerHanoiWrapper` function to understand the data format.

Should there be a clarification that each list is a state of three pegs?

**Comment by tsunghsienlee** [comment]
We just update the book to have this reflected.  Close the issue now.
