### ISSUE TITLE
The binary tree node doesn't have required reference to parent node

### ISSUE THREAD

**Issue by fantauzzi** [adnanaziz/EPIJudge#100]
As per problem in section 10.9, the binary tree node should have a reference to its parent. However, in the code it only has references to left and right children, see binary_tree_node.h and tree_inorder.cc

**Comment by tsunghsienlee** [comment]
Hi @fantauzzi ,

Thanks for your question, and we really appreciate it. For a binary tree problem, given the access to parent or not is like the problem requirement. There is no strict requirement saying every binary tree problem gives the parent node reference. Normally, you won't have access of that, and every now and then, you will have access to parent node (like 10.9 you pointed to).
