### ISSUE TITLE
cpp h index solution

### ISSUE THREAD

**Issue by yuxiang-zhang** [adnanaziz/EPIJudge#108]
There is a small issue with this solution for the introduction interview problem. 
https://github.com/adnanaziz/EPIJudge/blob/1e03a0c4e3ac033f1814e31c817e3a9889035aa3/epi_judge_cpp_solutions/h_index.cc#L10-L11

The variable `n` is declared but not used in the `for` loop condition.

**Comment by tsunghsienlee** [comment]
Hi @yuxiang-zhang ,

We do use _n_ in our solution, and you shall see that in https://github.com/adnanaziz/EPIJudge/blob/1e03a0c4e3ac033f1814e31c817e3a9889035aa3/epi_judge_cpp_solutions/h_index.cc#L12
