### ISSUE TITLE
Confusing Title for problem 9.14 in Python edition of EPI

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#111]
The question 9.14 says 

> "Form a linked list from the leaves of a binary Tree"

But the code provided in the book as well as in this repo: https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_python_solutions/tree_connect_leaves.py

create a normal list, not a linked list and present it as an output, which seems like a disconnect

**Comment by adnanaziz** [comment]
Good catch! #thanks @deveshks - we have updated the problem statement.

**Comment by deveshks** [comment]
I assume you will update the problem statement in the next edition of the book?
