### ISSUE TITLE
Typo on Page 163 for Python edition of the book

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#113]
There is a typo on Page 163 for Python edition of the book.

`Note that the built-in hash() function can greatly simplify the implementation of a hash function
for a user-defined class, i.e., implementing __hash(self)__`

The dunder function signature `__hash(self)__` is incorrect and should change to `__hash__(self)`

**Comment by tsunghsienlee** [comment]
Hi @deveshks ,

Thanks for your report, and it will be released in the next version.
