### ISSUE TITLE
IsTreeBalanced Java early termination

### ISSUE THREAD

**Issue by marialopezlatorre** [adnanaziz/EPIJudge#117]
Whenever I try to run IsTreeBalanced, the program terminates with errors without any further information.

Debugging the code shows that it never invokes the function. 

I'm able to get the following value of args in a specific version of Eclipse (4.9.0) if I stop the execution within main, but not elsewhere:
"Detail formatter error: Evaluations must contain either an expression or a block of well-formed statements."

I've tried this in the following IDEs:
Eclipse 4.9.0
Eclipse 4.13.0
IJ CE 2019.2.4

I've tried to spot differences between this particular case and the rest, and nothing seems to stand out to my (fairly unfamiliar) eyes, but any assistance would be much appreciated!

**Comment by tsunghsienlee** [comment]
@Hi @marialopezlatorre ,

Do you try to run on other problems and is this issue happened still?

Also, our framework requires Java 10 as listed in our page, and you shall check your Java compiler version.

**Comment by marialopezlatorre** [comment]
Thanks for the quick response @tsunghsienlee !

Running other problems before and after didn't fix the issue. As for the framework version, my understanding was 10+, so currently running on 11.0.1. 

Let me try on 10 and give an update.

**Comment by marialopezlatorre** [comment]
Nope, same situation with JDK 10.0.2. Only info I get without digging is a failed exit (code 1).
I was digging around with other tree test exercises and found what the issue is (it had to be the only difference, as those were working!). 
I'm used to adding auxiliary methods to the top, so the test couldn't find the class... 🤦‍♀️

Despite feeling a bit silly, I'm happy I could move forward! Thanks for your help anyway!

**Comment by metopa** [comment]
@marialopezlatorre It seems like you've added your code between the `@EpiTest` annotation and the tested function. Each annotation directly relates to the next method, so that could be the reason.
