### ISSUE TITLE
Buy And Sell A Stock Twice - Unnecessary restriction

### ISSUE THREAD

**Issue by zorro786** [adnanaziz/EPIJudge#118]
There is a restriction on this problem that says "The second buy must be made on another date after the first sale". Without loss of generality one can prove that if two transactions happen such that the second buy happens on the same day as first sale, the two transactions can be replaced by a single transaction giving you the same amount of profit.

For example:

0, 1, 2

Different scenarios:
First stock : Buy at 0, Sell at 1
Second stock: Buy at 1, Sell at 2
Total profit = 2

These two transactions can be replaced with a single buy and sell at 0 and 2 respectively giving the same profit.

The point I am making here is that the restriction doesn't change the outcome of solution even if it is not honored.

**Comment by zorro786** [comment]
M[i] = F[i] + B[i] is a valid algorithm (in addition to F[i-1] + B[i] defined in text book).

**Comment by adnanaziz** [comment]
nice catch @zorro786, thank you for helping us refactor this solution. we've made the changes, they will be reflected in the next release.
