### ISSUE TITLE
nitpicking: python 13.11 implement fast sorting algorithm might not be stable

### ISSUE THREAD

**Issue by TomatoCream** [adnanaziz/EPIJudge#121]
I'm nit picking here but ...
Solution to 13.11 references merge sort from 7.1
L1.data < L2.data preferentially selects L2 when L1 and L2 are equal so would end up reordering the elements.

consider L1.data <= L2.data

**Comment by tsunghsienlee** [comment]
Hi @TomatoCream ,

Very good observation, and in fact this is an inconsistency between our Python code vs. C++ (https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_cpp_solutions/sorted_lists_merge.cc) and Java (https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_java_solutions/epi/SortedListsMerge.java) codes.

Thanks for reporting this, and please keep up this good work.

This fix will be release in the next major release.
