### ISSUE TITLE
How to understand the EPI Java Test FrameWork

### ISSUE THREAD

**Issue by prash-kr-meena** [adnanaziz/EPIJudge#123]
Hey, thanks for sharing this great project with us.
I just wanted to know how could i understand the TEST framework (like the whole project how all this works as one piece). What i wanted to know i should  i start reading the code. from where should i start reading the code.

i looked the git commits, hoping i would see the code in multiple commits so i could  figure out how it started and then how it build on top of that, but then i found that all the major code was pushed in single commit only.

**Comment by tsunghsienlee** [comment]
Hi @prash-kr-meena ,

Because we have our internal project so you won't see the whole commit history for reason. I could tell you that since code is there, feel free to fork it and do any modifications if you want to study it.

**Comment by prash-kr-meena** [comment]
Ok thanks 👍

**Comment by metopa** [comment]
@prash-kr-meena I would like to add, that the simplest way to learn how the framework works internally is just to step in it with a debugger. Conceptually, not that many things are going on: 

1. The tested function signature is inspected to get its parameter types
2. Parameter parsers are for the test file are build based on this data
3. Each test case is parsed from the test file and is fed into the function
4. Function result is checked with the expected
5. Some bookkeeping is done in the end

The main effort was put to make this as generic as possible to cover the variety of algorithms we have in the judge.
