### ISSUE TITLE
LruCache.java testing expects -1 instead of null

### ISSUE THREAD

**Issue by amageed** [adnanaziz/EPIJudge#14]
Working on [LruCache.java](https://github.com/adnanaziz/EPIJudge/blob/3d45fb82bb947c474b6c2d9e3985b28f0beb1772/epi_judge_java/epi/LruCache.java) and returning `null` from the `lookup` function, as shown in the book, will result in a `NullPointerException`. It works fine if `-1` is returned instead.

**Comment by tsunghsienlee** [comment]
We update the book to reflect this so those APIs are more clear.
