### ISSUE TITLE
Incorrect code in Problem 21.11 in Python Book

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#140]
For the problem 21.11 `Function Arguments`, the last piece of code which explains default arguments has a bug

```
def read_file_as_array_buggy(filename, default=[]):

    try:
        filehandle = open(filename)
        return filename.read().split()
    except Exception:
        return default

def read_file_as_array_works(filename, default=None):

    if default is None:
        default = []
    try:
        filehandle = open(filename)
        return filename.read().split()
    except Exception:
        return default
```
In both functions, we should be doing `return filehandle.read().split()` instead of `return filename.read().split(), otherwise we are calling `read()` on the filename string which doesn't make sense, whereas we should be calling read on the filehandle

**Comment by tsunghsienlee** [comment]
This definitely is a valid bug that we shall use `filehandle` otherwise this is just a no-op. Thanks for this report, and this will be released in the next edition.

**Comment by deveshks** [comment]
Agreed. I will close the issue now since you have identified the bug
