### ISSUE TITLE
Potential bug in Problem 14.4 in Python edition

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#141]
For problem 14.4 `Compute the LCA in BST`, the text states that 

> without loss of generality assume the key at s is smaller. (Since the problem specified keys are 
> distinct, it cannot be that s and b hold equal keys.)

But what if the key s is bigger? The code would not work in that case. Perhaps the assumption here needs to be stated more clearly, or code needs to be fixed to cover the specific case

**Comment by tsunghsienlee** [comment]
Text could be improved here, as you could see https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_python_solutions/lowest_common_ancestor_in_bst.py#L9 where we explicitly mentioned the precondition. We will reword that in the next edition.

**Comment by deveshks** [comment]
Hi @tsunghsienlee 

I didn't see that the comment in the code already address it. As you mentioned, rewording the text to match the code will fix it
