### ISSUE TITLE
9.4 solution - wrong depth calculation

### ISSUE THREAD

**Issue by srikanthumich** [adnanaziz/EPIJudge#143]
Shouldn't it be `while node0.parent` instead of `while node0`? Given a single root node, the present code gives a depth of 1 (instead of 0).
`while node0.parent:
      depth_0 += 1
      node0 = node0.parent`

**Comment by tsunghsienlee** [comment]
Hi @srikanthumich ,

Someone reported this before at https://github.com/adnanaziz/EPIJudge/issues/110

**Comment by srikanthumich** [comment]
> Hi @srikanthumich ,
> 
> Someone reported this before at #110

Ohh sorry, I didn't see that. Thanks for the quick turnaround.
