### ISSUE TITLE
is_string_permutable_to_palindrome.tsv corrupt?

### ISSUE THREAD

**Issue by wilderfield** [adnanaziz/EPIJudge#155]
This is a **specific problem**

Problem: is_string_permutable_to_palindrome : Problem 13.1 in the book

- Please **classify issues**
(3.) Buggy test or buggy code, e.g.,  [tests for permutation problem have nonpermutation inputs](https://github.com/adnanaziz/EPIJudge/issues/57)

This is a strange issue, The test tsv file in the master branch does not seem to match what I can see in the web browser. As if the repo is some how corrupt? I've never seen something like this before.

This test sample is incorrect, as it is an odd length of valid characters, with 1 character having an odd count.

acpaa mnn aa alpaaanl    man    false   TODO

```
bryanloz@xsjfislx22:~/EPIJudge$ git branch
  dev
* master
bryanloz@xsjfislx22:~/EPIJudge$ head test_data/is_string_permutable_to_palindrome.tsv
string  bool
itnrsg  false   TODO
a    planaamnnaaa mcpaala n     true    TODO
 ibaal b  awr lsewesei ea       true    TODO
ya a rrya       true    TODO
c  raacrea      false   TODO
        true    TODO
srr  sro a ewaieo ssew ie       true    TODO
acpaa mnn aa alpaaanl    man    false   TODO
 erao tonateff evoorn  ev       true    TODO
```

By better solution we mean something that is (1.) more **idiomatic**; (2.) **faster** (from a complexity perspective, or in practical settings); or  (3.) easier to **understand**.
 - If you have a complete solution that is better solution, please consider using a [pull request](https://github.com/adnanaziz/EPIJudge/pulls). (If possible, please provide the solution for C++, Java, and Python.)
 - If the problem is with installation or execution, please give system information, i.e., OS, and language and build environment (including versions).
 - Please describe the behavior you see, including screenshots (you can use Google Drive, GitHub, or [Imgur](https://imgur.com/) to upload images and link to them); as well as the expected behavior.
 - For bugs, if possible please provide a reproducible test case that is the bare minimum necessary to generate the problem.

Because of our build process we cannot **directly accept PRs** by merging into the master branch. Instead please send PRs against the dev branch.
  - The reason for this is that we have a single source of truth, which is the complete solution that we annotate with markers that are used to generate the solution that goes inline in the book as well as the skeleton for the judge. (Here is a [snippet](https://imgur.com/nN6nbVL) of a source program, note the markers.)

**Comment by tsunghsienlee** [comment]
Could you sync with the the master branch as I could see you have an outdated branch; therefore, the issue you mentioned seems irrelevant.

The test data I see now is quite different from your https://github.com/adnanaziz/EPIJudge/blob/master/test_data/is_string_permutable_to_palindrome.tsv

**Comment by wilderfield** [comment]
I cloned the repo for the first time within the past two weeks.

The test data directory hasn’t changed in two months.

I don’t understand why my clone isn’t matching what is shown in the web
browser.

I cloned twice in two separate paths and see the problem in both clones.

**Comment by tsunghsienlee** [comment]
Sorry that it seems you have some git issue that I could not help on. However, it is not that hard if you try to figure out how to merge branches from remote with your local one I guess.

**Comment by tsunghsienlee** [comment]
Since you described does not match https://github.com/adnanaziz/EPIJudge/blob/master/test_data/is_string_permutable_to_palindrome.tsv so I will close this issue now.
