### ISSUE TITLE
Incomplete test cases for "Test for cyclicity" / "is_list_cyclic.cc"

### ISSUE THREAD

**Issue by SunHaozhe** [adnanaziz/EPIJudge#158]
This is a specific problem.

The problem name is `Test for cyclicity`, which corresponds to `is_list_cyclic.cc`

The test cases are not complete such that some wrong solutions could be falsely classified as correct ones (false negative).

As an example, the following C++ solution is not correct.
```c++
shared_ptr<ListNode<int>> HasCycle(const shared_ptr<ListNode<int>>& head) {
  if(head == nullptr || head->next == nullptr) return nullptr;
  shared_ptr<ListNode<int>> fast = head, slow = head;
  while(true){
    for(int i = 0; i < 2; i++){
      fast = fast->next;
      if(fast == slow) return fast;
      if(fast == nullptr) return nullptr;
    }
    slow = slow->next;
  }
  return nullptr;
}
```
However it passed all tests, as shown here:
<img width="1280" alt="false_negative" src="https://user-images.githubusercontent.com/26926814/73273690-64283f00-421f-11ea-8193-c574d6b1dc77.png">

Consider adding the following two test cases. The second test case comes from [Leetcode 142. Linked List Cycle II](https://leetcode.com/problems/linked-list-cycle-ii/):
```
[1,2,3,4,5]
1
```
```
[-21,10,17,8,4,26,5,35,33,-7,-16,27,-12,6,29,-12,5,9,20,14,14,2,13,-24,21,23,-21,5]
24
```

**Comment by tsunghsienlee** [comment]
Hi @SunHaozhe ,

The algorithm in your code is a correct one so that is the reason it passed the test case. About the two test cases you mentioned, your algorithm and the solution both find cycle in it, and the second test case is not a valid one, and you shall check the testing framework code to see how it parses the test data.
