### ISSUE TITLE
Since JavaScript is so popular, can you make a judge program for it?

### ISSUE THREAD

**Issue by jianlin** [adnanaziz/EPIJudge#162]
Since JavaScript is every where, and interviewers generally accept JavaScript as solutions, and sometimes interviewers test candidates for vanilla Javascript or NodeJS programming skills, can you create a judge program for it too.

@metopa

**Comment by tsunghsienlee** [comment]
Hi @jianlin ,

We did our survey before, and the top three programming languages for interviews are actually what we have now. I would say Javascript and Go are tied at 4th place. Sadly that we are short on hands on implementing solutions in other languages but keep it high quality so we have to rely on community to do that.

**Comment by jianlin** [comment]
> Hi @jianlin ,
> 
> We did our survey before, and the top three programming languages for interviews are actually what we have now. I would say Javascript and Go are tied at 4th place. Sadly that we are short on hands on implementing solutions in other languages but keep it high quality so we have to rely on community to do that.

Thank you Tsung Hsien.  I love Taiwan by the way.
@tsunghsienlee

**Comment by dangdennis** [comment]
For my own personal needs, I'm working on a fork to add a test suite for the javascript side with Deno. It'll ensure the easiest way to get started without external 3rd party dependencies.
