### ISSUE TITLE
Apply Permutation

### ISSUE THREAD

**Issue by BZAghalarov** [adnanaziz/EPIJudge#163]
Hi,

Following code from "5.10 Permute The Elements of an Array" .
This code snippet is not find in github code repo but it is given in book.
As you see the last 2nd line from code is not syntactically true.Because "else" condition has not if part.
Please help me to make code workable.

P.S At the same time I am interested in that why this solution doesn't exists in git?
```
def apply_permutation(perm, A):
    def cyclic_permutation(start, perm, A):
        i, temp = start, A[start]
        while True:
            next_i = perm[i]
            next_temp = A[next_i]
            A[next_i] = temp
            i, temp = next_i, next_temp
            if i == start:
                break

    for i in range(len(A)):
        # Traverse the cycle to see if i is the minimum element
        j = perm[i]
        while j != i:
            if j<i:
                break
            j = perm[j]
        else:
            cyclic_permutation(i, perm, A)

```

**Comment by tsunghsienlee** [comment]
Hi @BZAghalarov ,

In the later version of the book, we removed this since it is not that useful in the context of the problem, and we moved it to variant instead.
