### ISSUE TITLE
CPP version of Elias gamma coding problem is missing

### ISSUE THREAD

**Issue by FarsanRashid** [adnanaziz/EPIJudge#168]
**specific problem**

Could not find cpp file for problem **ELIAS GAMMA CODING** problem from chapter five. Are all problems from the book available in the repository?

**Comment by tsunghsienlee** [comment]
Hi @FarsanRashid ,

We removed this problem in the later version so that is the reason you would not find this in repository. IF you want, feel free to send me an email as I still keep this.
