### ISSUE TITLE
Missing problem Invert A Permutation

### ISSUE THREAD

**Issue by FarsanRashid** [adnanaziz/EPIJudge#170]
The version of the book I am reading has problem **Invert A Permutation** but it is not available in the current repository, Can I get the problem from somewhere else?

**Comment by tsunghsienlee** [comment]
Hi @FarsanRashid ,

We did not provide code even back to the time we had that problem; there was only text solution (as you could see in your book as well) at that time. That is the reason so we could not provide any code here.
