### ISSUE TITLE
max_water_trappable.py fails on the book's solution

### ISSUE THREAD

**Issue by ataki** [adnanaziz/EPIJudge#23]
First, thanks for creating this. It's been very helpful for my personal interviewing studies!

After implementing both the book's solution and my solution, I've discovered that `max_water_trappable.py` fails for both. However, my solution agrees with the book's solution for the first test case.

Could there be some mistake with the test cases for this problem?

```
Test FAILED (   1/1001) [  25 us] 
	Arg 1: [0, 1, 2, 1, 3, 4, 4, 5, 1, 2, 0, 3, 1]
	Expected: 7
	Result:   30
	Explanation: Example in the book
```

The implementation the book gives is:

```py
def calculate_trapping_water(heights):
    i, j, max_water = 0, len(heights) - 1, 0
    while i < j:
        width = j - 1
        max_water = max(max_water, width * min(heights[i], heights[j]))
        if heights[i] > heights[j]:
            j -= 1
        else:
            i += 1
    return max_water
```

**Comment by tsunghsienlee** [comment]
@ataki You are using the the solution from "Compute the maximum water trapped by a pair of vertical lines" for "Trapping water" so it definitely won't work.

We haven't released the judge data for "Compute the maximum water trapped by a pair of vertical lines" yet but it shall arrives soon as we are still preparing the test data.

Feel free to let us know if you have any other problem.

**Comment by ataki** [comment]
my mistake, thanks for clarifying!

**Comment by EldanGS** [comment]
'max_water_trappable.tsv' @tsunghsienlee 

Test FAILED (   1/1001) 
Arguments
	heights:     [0, 1, 2, 1, 3, 4, 4, 5, 1, 2, 0, 3, 1]

Failure info
	explanation: Example in the book
	expected:    7
	result:      12


```
def calculate_trapping_water(heights):
    pillar_indices, max_rectangle_area = [], 0

    for i, h in enumerate(heights + [0]):
        while pillar_indices and heights[pillar_indices[-1]] >= h:
            height = heights[pillar_indices.pop()]
            width = i - pillar_indices[-1] - 1 if pillar_indices else i
            max_rectangle_area = max(max_rectangle_area, height * width)
        pillar_indices.append(i)

    return max_rectangle_area
```

**Comment by lalwanivikas** [comment]
@EldanGS dude i think this code is for largest rectangle in histogram problem. max trapped water is a different problem.

**Comment by EldanGS** [comment]
@lalwanivikas my bad, I have a mistake.
