### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: config.json file not found

### ISSUE THREAD

**Issue by smellme** [adnanaziz/EPIJudge#31]
After cloning the EpiJudge I'm getting the following error when running any of the java files:

Exception in thread "main" java.lang.RuntimeException: config.json file not found
	at epi.test_framework.GenericTest.genericTestMain(GenericTest.java:36)
	at epi.test_framework.GenericTest.runFromAnnotations(GenericTest.java:156)
	at epi.BinomialCoefficients.main(BinomialCoefficients.java:16)

I'm using Eclipse and I followed the import process. I tried with Java 9.04 and 8.152. This is on the latest release of EpiJudge from 2018-03-27. The previous version from 2018-01-30 doesn't have this problem
![clipboard01](https://user-images.githubusercontent.com/36992967/38109656-8675c5d4-33a1-11e8-990a-b9f76fb45750.jpg)

**Comment by tsunghsienlee** [comment]
Hi @smellme ,

Thanks for the report, and it is because we add a new configuration file recently but we forget to add that.  I have fixed that in https://github.com/adnanaziz/EPIJudge/commit/ff57394ccc32f5e0b92b76743e6b9fb820f80228.

Please update your EPIJudge to the latest version.

**Comment by smellme** [comment]
works now, thank you
