### ISSUE TITLE
Can't build cpp solution in Visual Studio 2017

### ISSUE THREAD

**Issue by prepperoni** [adnanaziz/EPIJudge#36]
So I followed the steps performed in the youtube video for setting up visual studio 2017 for cpp problems. But when I select "Start without debugging" I get this popup saying my project is out of date and asking whether I want to build them: 
![popup](https://user-images.githubusercontent.com/37825069/39346250-f51f0516-49a1-11e8-9683-c58665d2da34.JPG)

When I select "Yes", I get this error: 
![attempt_to_build_count_bits](https://user-images.githubusercontent.com/37825069/39346295-34c522ea-49a2-11e8-8f9d-4272d69025c0.JPG)

**Comment by philipcraig** [comment]
This internal compiler crash no longer occurs with Visual Studio 2017 15.7.0 Preview 5.0

**Comment by metopa** [comment]
@philipcraig Thank you for trying the Preview version. We'll mention it in the README.

**Comment by prepperoni** [comment]
Thanks @philipcraig . I was able to successfully build the project with the preview version as you had mentioned :)
