### ISSUE TITLE
two_sum test data (two_sum.tsv) incorrect expected values?

### ISSUE THREAD

**Issue by girishpai** [adnanaziz/EPIJudge#4]
It looks like few of the test cases have incorrect expected bool values. 

For example the 1st test case : 
[6, -7, -3, 3, -3, 4, -5]	3	false	TODO

There are two entries (of values 6 and -3) in the array which add upto the target 3. Still the expected value is false. 

Apologies if my interpretation of the question was incorrect.

**Comment by EldanGS** [comment]
Hi @tsunghsienlee ,

The same problem, but the answer doesn't right.
Could you explain, how we will use 1 values two times(is it legal?)? In my opinion that is not the right way to solving this problem.

Test FAILED (  53/1005) 
Arguments
	A:        [-2, -1, 1, 4]
	t:        8

Failure info
	expected: True
	result:   False


`def has_two_sum(A, t):
    left, right = 0, len(A) - 1
    while left < right:
        current_sum = A[left] + A[right]
        if current_sum > t:
            right -= 1
        elif current_sum < t:
            left += 1
        else:
            return True

    return False`

**Comment by rishab-pdx** [comment]
@EldanGS The statement of the problem says it is not necessary that the the numbers be distinct
