### ISSUE TITLE
Is Visual Studio 2015 not supported now? 

### ISSUE THREAD

**Issue by vmishra22** [adnanaziz/EPIJudge#41]
I am unable to build due to errors in test framework: 
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Build started 5/4/2018 9:42:43 AM.
1>     1>
1>PrepareForBuild:
1>         Creating directory "C:\Users\v1a\epi\EPIJudge\epi_judge_cpp\vs\Debug\".
1>         Creating directory "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
1>       InitializeBuildStatus:
1>         Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
1>       CustomBuild:
1>         Checking Build System
1>         CMake does not need to re-run because C:/Users/v1a/epi/EPIJudge/epi_judge_cpp/vs/CMakeFiles/generate.stamp is up-to-date.
1>       FinalizeBuildStatus:
1>         Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
1>         Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.14
2>------ Build started: Project: count_bits, Configuration: Debug Win32 ------
2>Build started 5/4/2018 9:42:43 AM.
2>     1>
2>PrepareForBuild:
2>         Creating directory "count_bits.dir\Debug\count_bits.tlog\".
2>       InitializeBuildStatus:
2>         Creating "count_bits.dir\Debug\count_bits.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
2>       CustomBuild:
2>         Building Custom Rule C:/Users/v1a/epi/EPIJudge/epi_judge_cpp/CMakeLists.txt
2>         CMake does not need to re-run because C:/Users/v1a/epi/EPIJudge/epi_judge_cpp/vs/CMakeFiles/generate.stamp is up-to-date.
2>       ClCompile:
2>         count_bits.cc
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(68): error C3250: 'result': declaration is not allowed in 'constexpr' function body
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(18): note: see reference to function template instantiation 'int FirstFalseArg<>(bool)' being compiled
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(69): error C3256: 'result': variable use does not produce a constant expression
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(64): error C3259: 'constexpr' functions can only have one return statement
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(18): error C2131: expression did not evaluate to a constant
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(18): note: function violates 'constexpr' rules or has errors
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(18): note: see usage of 'FirstFalseArg'
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(19): error C2131: expression did not evaluate to a constant
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(19): note: function violates 'constexpr' rules or has errors
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(19): note: see usage of 'FirstFalseArg'
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(20): error C2131: expression did not evaluate to a constant
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(20): note: function violates 'constexpr' rules or has errors
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(20): note: see usage of 'FirstFalseArg'
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(21): error C2131: expression did not evaluate to a constant
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(21): note: function violates 'constexpr' rules or has errors
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(21): note: see usage of 'FirstFalseArg'
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(22): error C2131: expression did not evaluate to a constant
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(22): note: function violates 'constexpr' rules or has errors
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(22): note: see usage of 'FirstFalseArg'
2>     1>
2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility(495): error C2971: 'std::tuple_element': template parameter '_Index': '_Index': a variable with non-static storage duration cannot be used as a non-type argument
2>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility(416): note: see declaration of 'std::tuple_element'
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(202): note: see declaration of '_Index'
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(202): note: see reference to class template instantiation 'tuple_element_t<default_valueAttribute,std::tuple<char,short,int,long>>' being compiled
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta.h(208): note: see reference to class template instantiation 'SubTuple<std::tuple<char,short,int,long>,0,4>::Impl<0,std::integer_sequence<std::_Ty,0,1,2,3>>' being compiled
2>                 with
2>                 [
2>                     _Ty=std::size_t
2>                 ]
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(38): note: see reference to class template instantiation 'SubTuple<std::tuple<char,short,int,long>,0,4>' being compiled
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(32): note: see reference to class template instantiation 'FunctionalTraits<void (__cdecl *)(int,int)>' being compiled
2>         c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(29): note: see reference to class template instantiation 'FunctionalTraits<void (__cdecl *)(TimedExecutor &,int)>' being compiled
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(40): error C2338:
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(55): error C2338:
2>     1>
2>c:\users\v1a\epi\epijudge\epi_judge_cpp\test_framework\test_utils_meta_test.h(59): error C2338:
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:00.97
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by cmercur2** [comment]
The specific implementation of test meta-programming that was recently added is not supported by MSVC.

Just checkout a previous commit from Dec  30th:
git checkout 345adde576c8f29006c545d00aa633967038fd6d

**Comment by metopa** [comment]
@vmishra22 @cmercur2 You should try VS2017 15.7.0 Preview 5.0 or MinGW complier. 

Sadly, not even the release version of VS2017 is supported - the compiler contains a bug that makes it impossible to compile the project. I strongly suggest you not to fallback to any of old releases - we add many fancy features and fix problems with every beta release. BTW, **the next release is expected to be in the next few days** - the only thing left is Windows testing. I'll let you know what compilers are currently supported on Windows.

**Comment by metopa** [comment]
@vmishra22 In the new release we've listed detailed requirements on Windows compilers in README. Please, open a new issue if you still have problems with this release.
