### ISSUE TITLE
Question on 14.9

### ISSUE THREAD

**Issue by bixuanzju** [adnanaziz/EPIJudge#46]
Q14.9 (`DescendantAndAncestorInBst`) asks us to determine if two given nodes are a *proper* ancestor and a *proper* descendant of the middle node. According to the explanation, if one of the two is equal to the middle, then it should return false because one of them is not a *proper* ancestor/descendant. One of the test cases is as follows:
```
Test FAILED (441/959) 
Arguments
	arg1:     ["18", "9", "29", "5", "14", "21", "34", "1", "null", "null", "17", "null", "25", "null", "35"]
	arg2:     17
	arg3:     9
	arg4:     9

Failure info
	expected: true
	result:   false
```
If I am not mistaken, the expected result should be false, because the third argument equal to the middle node (the forth argument). Did I misunderstand the question?

**Comment by tsunghsienlee** [comment]
Hi @bixuanzju,

You might want to update your client as I cannot find this test case now.

**Comment by bixuanzju** [comment]
Hi @tsunghsienlee 

I found that https://raw.githubusercontent.com/adnanaziz/EPIJudge/master/test_data/descendant_and_ancestor_in_bst.tsv

Search `["18", "9", "29", "5", "14", "21", "34", "1", "null", "null", "17", "null", "25", "null", "35"]	17	9	9	true	TODO`

**Comment by tsunghsienlee** [comment]
Hi @bixuanzju ,

Do you figure out what the problem is?

**Comment by bixuanzju** [comment]
@tsunghsienlee no, did you see my last comment, I found the test case in the repo

**Comment by madhuri7112** [comment]
I have the same issue. 
In case anyone is looking for a quick fix 
Open `EPIJidge/test_data/descendant_and_ancestor_in_bst.tsv`
Replace line 442 with 
`["18", "9", "29", "5", "14", "21", "34", "1", "null", "null", "17", "null", "25", "null", "35"]	17	9	9	false	TODO`

**Comment by tsunghsienlee** [comment]
Hi @madhuri7112 ,

We are fixing the test data and please wait for the next version of test data of this one. You could use the solution to add debug information to track how this works.
