### ISSUE TITLE
Incorrect Expectation on Test (2/97) for problem 13.5 (Render a Calendar)

### ISSUE THREAD

**Issue by JoshHumpherey** [adnanaziz/EPIJudge#49]
Input:  [[1, 5], [2, 7], [4, 5], [6, 10], [8, 9], [9, 17], [11, 13], [12, 15], [14, 15], [9, 10]]
Expected: 4
Result: 3

This input is the same as the book's base case/example except it adds an event that runs from 9-10. However, this only bumps up the event count from 2 -> 3. The expectation for this case should be a 3 and the example code should be checked because it gives an incorrect answer for this problem. Love the book, hope this helps!

EDIT: The example code sorts by endpoints and computes the maximum number of events starting and ending at any certain hour. However, just because an event ends at 9 does not mean it should be counted as an "ongoing" event as there will still only be 3 events going on during the 9-10 hour.

**Comment by magician03** [comment]
@JoshHumpherey - Hi

> However, just because an event ends at 9 does not mean it should be counted as an "ongoing" event as there will still only be 3 events going on during the 9-10 hour

This fact entirely depends on problem statement whether you need to consider end points as inclusive or exclusive. In case of real interviews, you need to confirm it with the interviewer. Depending upon this you need to change the sorting function to make sure if two different events begin and end at same, you first iterate over ending event thereby decrementing the count and then later incrementing the count.

Hope this helps!!

**Comment by tsunghsienlee** [comment]
Hi @JoshHumpherey ,

In this problem, the calendar event is defined as both ends are inclusive.  That is  the reason the result is 4 instead of 3.  Please let us know if you have any other questions.  We will add some text to clarify this in the next release of book.
