### ISSUE TITLE
When will the Python version EPIJudge works on Visual Studio Code?

### ISSUE THREAD

**Issue by goodgoodwish** [adnanaziz/EPIJudge#50]
Howdy,  Great job!

I hope you have a plan to make EPIJudge Running the judge using Visual Studio Code in near future.

Thanks,
Charlie

**Comment by magician03** [comment]
@goodgoodwish Hi, AFAIK, VSCode is just an editor. However, you can use integrated terminal to run programs within it and that way Python code samples work fine. Did you mean Visual Studio IDE or anything else ?

**Comment by goodgoodwish** [comment]
@magician03 Hi Diwakar, thanks for your quick reply. I'm not sure if this place is good for suggestions and questions.

Goto https://marketplace.visualstudio.com/items?itemName=ms-python.python

After you install this Python extension for Visual Studio Code, it turns VSCode into an Python IDE immediately.
This extension is super popular, 15,594,508 people installed it.   ^_^

You may have a look.

Thanks,
Charlie

**Comment by metopa** [comment]
@goodgoodwish Hi, what problems do you encounter when working in VS code?

**Comment by tsunghsienlee** [comment]
Hi Charlie,

I am a little confused about what you mean Python version works on Visual
Studio Code but you said there is no problem of using that.  What do you
mean using Visual Studio here because what our Python repository shall be
compatible with any editor.

Tsung-Hsien

**Comment by goodgoodwish** [comment]
Hi @tsunghsienlee Tsung-Hsien,

Thanks for your consideration.
I just hope the EPIJudge can be a vs code extension that is more user friendly.

Here is a VS code extension example,
https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

My thought is not mature yet, before I finish your book EPI.
I'm going to watch your talk in PyCon APAC 2018 too.
( Elements of Programming Interviews in Python - PyCon APAC 2018 )

Thanks,
Charlie 木匠
