### ISSUE TITLE
Does anyone face Java compiler issues after import into IntelliJ?

### ISSUE THREAD

**Issue by chanpal** [adnanaziz/EPIJudge#52]
Does anyone face Java compiler issues after import into IntelliJ?

/EPIJudge/epi_judge_java/epi/test_framework/GenericTestHandler.java
Error:(67, 22) java: cannot find symbol
  symbol:   method of(java.lang.reflect.Type[])
  location: interface java.util.List

/EPIJudge/epi_judge_java/epi/test_framework/serialization_traits/TraitsFactory.java
Error:(21, 42) java: cannot infer type arguments for java.util.HashMap<K,V>
  reason: cannot use '<>' with anonymous inner classes
Information:java: /Users/cpaladugula/code/EPIJudge/epi_judge_java/epi/test_framework/serialization_traits/TraitsFactory.java uses unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

/EPIJudge/epi_judge_java/epi/test_framework/TestUtils.java
Error:(30, 22) java: cannot find symbol
  symbol:   method of(java.lang.String[])
  location: interface java.util.List

**Comment by hieudt** [comment]
You can fix this issue by installing JDK 10 and set the Module language level to 9.

**Comment by chanpal** [comment]
I tried all combinations of JDK from 8,9 and 10. 

I just tried your suggested procedure of changing the Module Language level to 9. The behavior remains the same.

BTW, I am using IntelliJ 2018.1 version. JDK 8 and 10 installed.

**Comment by chanpal** [comment]
Thank you, Hieu. It solved the problem.

I was initially changed the values to default project structure expecting that it effects all projects including the current one, but it’s not. After changing the project’s project structure, I was able to make it work. Thanks!

[cid:8212DC2A-5027-419D-AFC7-8166AD9BC434]



On Aug 12, 2018, at 10:24 PM, Hieu Do <notifications@github.com<mailto:notifications@github.com>> wrote:


Below are the settings I'm using in IntelliJ, it can compile and run the judge perfectly.
[image]<https://user-images.githubusercontent.com/2525926/44013890-5d710d0a-9e7d-11e8-8ae0-792af0d92d6c.png>
[image]<https://user-images.githubusercontent.com/2525926/44013875-4051ffae-9e7d-11e8-927d-cfebb5520d7c.png>
[image]<https://user-images.githubusercontent.com/2525926/44013982-ecc1fb90-9e7d-11e8-8b9f-f5903b3190dc.png>
