### ISSUE TITLE
Line 17 in permutation.tsv is not a permutation

### ISSUE THREAD

**Issue by tddevlin** [adnanaziz/EPIJudge#57]
The input is [4, 2, 2, 4, 2], which is not a valid permutation.

**Comment by tddevlin** [comment]
In fact there are many invalid permutations in this test file.

**Comment by metopa** [comment]
Hello @tddevlin, it seems like you're talking about `next_permutation.tsv`. It is true that current tests are against the book definition of the problem. However, the presented algorithm seems to handle inputs with repetitions just well. I'll check on this with the book authors and either remove invalid tests or expand problem definition. Thank you

**Comment by adnanaziz** [comment]
@tddevlin: thanks for pointing this out. We've reworded the problem to reflect that the ask is to generate the lexicographical successor of the array. 

E.g., A = [1, 2, 3, 1], you should return [1, 3, 1, 2]; if the input is [2,2,4,1,3], you should return [2,2,4,3,1]. If there is no such array, e.g., the input is [3, 2, 1, 1], return the empty array.

**Comment by adnanaziz** [comment]
Closed with update to book and response to @tddevlin.
