### ISSUE TITLE
max_sum_subarray.py does not handle all negative numbers

### ISSUE THREAD

**Issue by Pradheesh** [adnanaziz/EPIJudge#62]
https://github.com/adnanaziz/EPIJudge/blob/master/epi_judge_python_solutions/max_sum_subarray.py

Does not handle all negative number list. 

The bounday conditions of mins and maxs = 0 does not work for this case.

**Comment by metopa** [comment]
@Pradheesh Thank you for pointing this out. I'll review it

**Comment by tsunghsienlee** [comment]
Hi @Pradheesh ,

It is a definition problem, normally, you could have a subarray of size 0. If we are allowed 0-sized subarray, the answer for all negative numbers is 0. In this problem we allow 0-sized subarray.

During interview, you shall double-checked this with your interviewer for sure.
