### ISSUE TITLE
Guideline for submitting better solutions

### ISSUE THREAD

**Issue by arvand** [adnanaziz/EPIJudge#66]
Since the book is becoming more popular, I was wondering if there is a guideline for submitting simpler and cleaner solutions with better comments and explanations? 
Also is there a to-do list of backlogs that we can contribute to?

**Comment by metopa** [comment]
@arvand If you have suggestions for the code itself, you can submit a PR with a modified version in `solution` folder. Try to provide new solution for all 3 languages. If you're speaking about the book text, you should contact @adnanaziz on this.
