### ISSUE TITLE
Why is the square root of 0 not 0 ?

### ISSUE THREAD

**Issue by Naman-Bhalla** [adnanaziz/EPIJudge#67]
Thanks for such a great book. While solving on EPI Judge I found this weird. Would be great if can be explained.
Thanks

https://github.com/adnanaziz/EPIJudge/blob/1e03a0c4e3ac033f1814e31c817e3a9889035aa3/test_data/real_square_root.tsv#L2215

**Comment by Naman-Bhalla** [comment]
I checked the parts of code that are causing result to be 0 v/s expected.

The following code runs correctly (Gives output 1.571727783679971e-162):

```
def square_root(x):
    left, right = (x, 1.0) if x < 1.0 else (1.0, x)

    while not math.isclose(left, right):
        mid = left + (right - left) / 2
        check = mid ** 2
        if check <= x:
            left = mid
        else:
            right = mid
    return  left
```

On the other hand, if I use "if check < x" instead of "<=", it fails (Gives output 0 for 0, which ideally should be correct ?).

```
def square_root(x):
    left, right = (x, 1.0) if x < 1.0 else (1.0, x)

    while not math.isclose(left, right):
        mid = left + (right - left) / 2
        check = mid ** 2
        if check < x:
            left = mid
        else:
            right = mid
    return  left
```
Arguments
	x:        0.0


```Failure info
	expected: 1.571727783679971e-162
	result:   0.0
```

**Comment by tsunghsienlee** [comment]
Hi @Naman-Bhalla ,

Thanks for your report, and this definitely is an ill-generated test data. I have removed that entry, and this change will be reflected in the next release. Thanks!
