### ISSUE TITLE
StopIteration leads to Critical error(RuntimeError): generator raised StopIteration [Python 3.7]

### ISSUE THREAD

**Issue by Naman-Bhalla** [adnanaziz/EPIJudge#69]
Hi !
As per PEP 0479 (https://www.python.org/dev/peps/pep-0479/) , there is a change in StopIteration handling inside generators.
Due to this, when we run tree_right_sibling.py (I haven't yet checked which other files are affected by this too, but it should be anywhere StopIteration is being used), it leads to a RunTime Error.
A quick solution is to just replace 
```
raise StopIteration
```

with

```
return
```

The above solution is also mentioned on the PEP:

> Here are some illustrations from the standard library.
>
>Lib/ipaddress.py:
>
>if other == self:
>   raise StopIteration
>Becomes:
>
>if other == self:
>    return

https://github.com/adnanaziz/EPIJudge/blob/1e03a0c4e3ac033f1814e31c817e3a9889035aa3/epi_judge_python/tree_right_sibling.py#L24

**Comment by metopa** [comment]
@Naman-Bhalla thank you for pointing this out. This will be adressed in the upcoming release.

**Comment by tsunghsienlee** [comment]
Hi @Naman-Bhalla ,

Many thanks for reporting this, and I have pushed a fix for this. It shall be released in next version.
