### ISSUE TITLE
string_transformation.cc gives away the approach

### ISSUE THREAD

**Issue by alf239** [adnanaziz/EPIJudge#70]
In line 7,
```
// Uses BFS to find the least steps of transformation.
```
gives pretty much all one needs to have in order to arrive at the solution; delete perhaps?

**Comment by metopa** [comment]
@alf239 Thank you for pointing this you, this will be fixed in the upcoming release

**Comment by tsunghsienlee** [comment]
Hi @alf239 ,

Very sharp eyes, and I just pushed a change to fix this, and it will be in the next release.
