### ISSUE TITLE
Cannot run any test cases in IntelliJ 

### ISSUE THREAD

**Issue by datracker** [adnanaziz/EPIJudge#74]
Hi, 
I cannot run any test cases due to 3 errors in epi/test_framework.

1. In ~/EPIJudge/epi_judge_java/epi/test_framework/GenericTestHandler.java the error is:
Error:(67, 22) java: cannot find symbol
  symbol:   method of(java.lang.reflect.Type[])
  location: interface java.util.List

2. In ~/EPIJudge/epi_judge_java/epi/test_framework/TestUtils.java
Error:(30, 22) java: cannot find symbol
  symbol:   method of(java.lang.String[])
  location: interface java.util.List

3. In ~/EPIJudge/epi_judge_java/epi/test_framework/serialization_traits/TraitsFactory.java
Error:(21, 42) java: cannot infer type arguments for java.util.HashMap<K,V>
  reason: cannot use '<>' with anonymous inner classes

Please help me. Thanks.

**Comment by capy-pl** [comment]
How did you fix this?

**Comment by 91Vallabh** [comment]
Any updates on how to fix this?
