### ISSUE TITLE
about one case of DoListsOverlab.java 

### ISSUE THREAD

**Issue by taojin1992** [adnanaziz/EPIJudge#76]
Book P101 (7.5 DoListsOverlab.java ): need more explanation on why "if one list is cyclic, and the other one is not, they cannot overlap.". They can still overlap when the cyclic part appears earlier in one list and they can share the following part without the circle.

**Comment by metopa** [comment]
List overlap means they have the same tail, that is from some node they start sharing the same nodes. At this point, you can't have 1 list being cycled, while the other one having a terminal node
