### ISSUE TITLE
Naming Inconsistency: between Problem name in book and filename.

### ISSUE THREAD

**Issue by Plotnus** [adnanaziz/EPIJudge#80]
Problem 6.1
The title for the problem in the text is "Interconvert strings and integers."
The exe and file name are `string_integer_interconversion` and "string_integer_interconversion.cc".

**Comment by Plotnus** [comment]
If you would like and open to accepting to pull requests let me know and I can take a swing at addressing this.

The project files for the different languages & IDE are the main part that would make this a bit more involved.

With C++ it's fine since we can generate them with CMake.

**Comment by metopa** [comment]
Hi @Plotnus, we know about the inconsistency. However, the book naming may change from release to release and it is impractical to enforce it there. You can use https://github.com/adnanaziz/EPIJudge#problem-to-program-mapping to find out the corresponding code name for a problem in the book.
