### ISSUE TITLE
Naming Mismatch: Problem 10.1

### ISSUE THREAD

**Issue by Plotnus** [adnanaziz/EPIJudge#82]
In the text problem 10.1 is called "Merge Sorted Files".
The testfile is called `sorted_arrays_merge.cc`.

The only way I found the file name was by peeking at the solution.

**Comment by alf239** [comment]
Problem is, since the solution files are in the book, too, the names are pretty much set in stone: renaming the solution (templates) will result in naming mismatch between the book and the repo.
