### ISSUE TITLE
Missing problems: parallel computing chapter has no problems in EPI

### ISSUE THREAD

**Issue by timaku** [adnanaziz/EPIJudge#88]
In the parallel computing chapter, these problems are no where to be found in EPI Judge. Like "The Readers-Writers Problem", #19.6 in my Java edition of EPI

**Comment by timaku** [comment]
This repo has it: https://github.com/gardncl/elements-of-programming-interviews
But it would be better if all problems were supported by the authors

**Comment by metopa** [comment]
Hi @timaku, as of today the testing framework does not support parallel programs. This may change in the future.
