### ISSUE TITLE
"Find the kth largest element" assumes distinct elements on the book, but arrays in test-data have duplicates.

### ISSUE THREAD

**Issue by giuscri** [adnanaziz/EPIJudge#90]
For problem 12.9, _Find the kth largest element_, the description says

> Assume entries are distinct .

But the related test data contains arrays such as `[12, -8, -8, 11, -9, 1, 7, -11, 2, -8, 1, 5, 2, -8]`, which contains `-8` 4 times for exemple.

---
Book version: `1.5.3`
HEAD of repository: 1e03a0c

**Comment by tsunghsienlee** [comment]
Hi @giuscri ,

We have removed this constraint in the later version of the book as we noticed that it does not need be that way. I noticed we still have a sentence in solution mentioning this constraint, and we will fix the solution text part later. Thanks for your reporting still.
