### ISSUE TITLE
"Compute a shortest path with fewest edges" is missing

### ISSUE THREAD

**Issue by fantauzzi** [adnanaziz/EPIJudge#95]
There is no support in the EPIJudge for problem "Compute a shortest path with fewest edges", see Sec. 19.11 of the C++ book. I can't find it listed int the README "Problem to Program Mapping", and also can't find it by grepping in the source code.

**Comment by metopa** [comment]
Hi @fantauzzi, thank you for using EPIJudge.
There are some problems that are not currently in the judge. We might support them in the future, but no particular plans there for now.
