### ISSUE TITLE
is_binary_tree_bst.py incorrect?

### ISSUE THREAD

**Issue by g-aaroncruz** [adnanaziz/EPIJudge#97]
In the EPI python book on page 214 for problem 14.1, the input is described as a BinarytreeNode object. Although, in the EPIJudge, the tree comes in as a array. Unless I misunderstood the problem this seems like a bug. 

![image](https://user-images.githubusercontent.com/10556148/59983154-ee952a00-95d0-11e9-9373-228a75937f9d.png)

**Comment by metopa** [comment]
Hi @g-aaroncruz 
The argument for `is_binary_tree_bst` is actually a binary tree. We just use a list format for displaying the tree
